# Kafka broker configuration
stepprflow:
  broker: kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}-workers
      auto-offset-reset: earliest
      concurrency: 1
    producer:
      acks: all
      retries: 3
    trusted-packages:
      - io.stepprflow.core.model
      - io.stepprflow.sample.model