spring:
  application:
    name: stepprflow-rabbitmq-sample

server:
  port: 8011

stepprflow:
  broker: rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    exchange: stepprflow.workflows
    prefetch-count: 10
    trusted-packages:
      - io.stepprflow.core.model
      - io.stepprflow.sample.model
  agent:
    server-url: http://localhost:8090
    auto-register: true
  monitor:
    web-socket:
      enabled: false

logging:
  level:
    io.stepprflow: INFO
    io.stepprflow.sample: DEBUG
    io.stepprflow.monitor: INFO
